require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops:
    enable
  Exclude:
    - 'app/views/**/*'
    - 'db/**/*'
    - 'bin/**/*'

Style/Documentation:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false
